token: "__LICHESS_TOKEN__"
url: "https://lichess.org/"
engine:
  dir: "."
  name: "__ENGINE_PATH__"
  protocol: "uci"
  ponder: true
  polyglot:
    enabled: true
  draw_or_resign:
    offer_draw_enabled: true
    resign_enabled: true
challenge:
  concurrency: 1
  sort_by: "best"
  accept_bot: true
  max_increment: 180
  min_increment: 0
  max_base: 1800
  min_base: 0
  variants: ["standard"]
  time_controls: ["bullet", "blitz", "rapid"]
  modes:
    - rated
    - casual
  rated_only: __RATED_ONLY__
matchmaking:
  allow_matchmaking: true
  challenge_initial_time:
    - 60
    - 120
    - 180
    - 300
  challenge_increment:
    - 0
    - 1
    - 2
    - 3
    - 5
messages:
  greeting: "__GREETING_MESSAGE__"
  goodbye: "__GOODBYE_MESSAGE__"
  greeting_spectators: "__SPECTATOR_MESSAGE__"
